version: '3.0'

services:
  grafana:
    container_name: 'masch712-bpmnheatmap-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.2.5}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/masch712-bpmnheatmap-panel
      - ./provisioning:/etc/grafana/provisioning
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    networks:
      - elastic
    ports:
      - 5601:5601
networks:
  elastic:
